services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: DS_service_db
      POSTGRES_USER: DS_user
      POSTGRES_PASSWORD: DS_password
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
